### ISSUE TITLE
Modify the design of the Cocktail Details Page

### ISSUE THREAD

**Issue by SaraVahidinovin** [annagabain/fabulous-sheriffs-grupprojekt-react#94]
- [x] **Task:**
  Add labels for detailed information such as category, tags, and the type of glass the cocktail is served in, displaying them on separate rows. 
Ensure ingredient names are visually identifiable as clickable links on the Cocktail Details Page (the current tag is `<p>`).  
  - **Priority:** Medium  
  - **Value Points:** 3  
  - **Estimated Time:** 2 hours  
  - **Tags:**  
  - **Assignee:** Anna

**Comment by annagabain** [comment]
@SaraVahidinovin @IsabellePar I have a quick placement question. Where do you want the tags? The task description here says one per raw, so I programmed in this current commit. But the mockup had them highlighted orange under the cocktail image.


![Image](https://github.com/user-attachments/assets/908483b1-1b5d-4712-b423-7184885c9a4a)

vs.

![Image](https://github.com/user-attachments/assets/80e4765b-5198-4c77-a6bf-2840ee16e3d8)

**Comment by annagabain** [comment]
this is the live version now, any comments before I create a new pull request?
@SaraVahidinovin @IsabellePar 

![Image](https://github.com/user-attachments/assets/e6527fac-d3b4-42d3-9a2a-97d46bf59387)
